### ISSUE TITLE
EventListener.spec.triggers[].template.name is obsolete

### ISSUE THREAD

**Issue by InfoSec812** [redhat-scholars/tekton-tutorial#61]
https://github.com/redhat-scholars/tekton-tutorial/blob/93323dbff64913b537400840fb6696491e5b90f8/triggers/gitea-eventlistener.yaml#L13

It should be:

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitea-webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: tekton-greeter-webhook
      bindings:
        - ref: gitea-triggerbinding
      template:
        ref: tekton-greeter-trigger-template
```
